version: '3'

services:
  payload:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - media-storage:/app/public/media

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  media-storage:
  mongo-data: